# Generated by Django 4.2.16 on 2024-12-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_auto_20241201_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
