# Generated by Django 4.2.16 on 2024-12-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='index',
            field=models.CharField(default='F01', max_length=20),
        ),
    ]
