# Generated by Django 4.2.16 on 2025-03-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_adm2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('sta_id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('stabbr', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
    ]
