# Generated by Django 5.2 on 2025-04-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryDimension',
            fields=[
                ('lb_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'library_dimension',
                'managed': False,
            },
        ),
    ]
