# Generated by Django 3.1.2 on 2024-11-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Indicator', models.CharField(default='N/A', max_length=255)),
                ('Rank_2010', models.IntegerField()),
                ('Rank_Growth_2010_2019', models.IntegerField()),
                ('Rank_2019', models.IntegerField()),
                ('Rank_Growth_2019_2023', models.IntegerField()),
                ('Rank_2013', models.IntegerField()),
                ('Rank_2023', models.IntegerField()),
                ('State', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
            ],
        ),
    ]
