# Generated by Django 4.2.16 on 2024-11-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_rankingdata_rank_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
