# Generated by Django 2.1.5 on 2024-12-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_rankingdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
