# Generated by Django 5.1.4 on 2024-12-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_rankingdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
