# Generated by Django 3.1.2 on 2024-11-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('indicator', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ['state', 'year'],
                'unique_together': {('state', 'indicator', 'year')},
            },
        ),
    ]
