# Generated by Django 3.1.2 on 2024-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('indicator', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
