# Generated by Django 3.1.2 on 2024-11-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_ranking_indicator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ranking_indicator',
            new_name='rankings_indicator',
        ),
    ]
