# Generated by Django 4.2.16 on 2024-11-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_auto_20241122_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rankings_indicator',
        ),
    ]
