# Generated by Django 4.2.16 on 2024-11-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_alter_economicdata_id_alter_indicator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
                ('indicator', models.CharField(max_length=200)),
            ],
        ),
    ]
