# Generated by Django 4.2.16 on 2024-11-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_groupname'),
        ('rankings', '0009_auto_20241129_0748'),
    ]

    operations = [
    ]
