# Generated by Django 4.2.16 on 2024-11-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0010_merge_0008_groupname_0009_auto_20241129_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='weight',
            field=models.FloatField(default=0.16666666666666666),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
