# Generated by Django 4.2.16 on 2024-11-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0011_groupname_weight_alter_indicator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorindex',
            name='weight',
            field=models.FloatField(default=0.04),
        ),
    ]
