# Generated by Django 2.1.5 on 2024-12-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0013_auto_20241201_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
