# Generated by Django 4.2.16 on 2024-12-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0014_auto_20241201_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indicatorindex',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
