# Generated by Django 5.1.4 on 2024-12-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0015_alter_economicdata_id_alter_groupname_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorindex',
            name='key',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatorindex',
            name='unit',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
