# Generated by Django 4.2.16 on 2024-12-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0018_alter_economicdata_id_alter_groupname_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=20)),
                ('STAREFP', models.CharField(max_length=10)),
                ('STUSPS', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
