# Generated by Django 4.2.16 on 2024-12-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0020_remove_state_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='STAREFP',
            new_name='r_id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='STUSPS',
            new_name='s_id',
        ),
    ]
