# Generated by Django 3.1.2 on 2024-11-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('agriculture', 'Nông nghiệp, lâm nghiệp và thủy sản'), ('mining', 'Khai khoáng'), ('manufacturing', 'Chế biến và chế tạo'), ('utilities', 'Sản xuất và phân phối điện, nước'), ('construction', 'Xây dựng'), ('retail', 'Bán buôn và bán lẻ; sửa chữa xe có động cơ'), ('transport', 'Vận tải kho bãi'), ('hospitality', 'Dịch vụ lưu trú và ăn uống'), ('ict', 'Thông tin và truyền thông'), ('finance', 'Hoạt động ngân hàng, tài chính và bảo hiểm'), ('science', 'Hoạt động chuyên môn, KHCN'), ('education', 'Giáo dục và đào tạo'), ('health', 'Y tế và hoạt động trợ giúp xã hội'), ('arts', 'Nghệ thuật, vui chơi, giải trí'), ('other', 'Ngành nghề khác')], max_length=50, verbose_name='Lĩnh vực kinh doanh')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('<5', '< 5 người'), ('5-9', '5 - 9 người'), ('10-49', '10 - 49 người'), ('50-199', '50 - 199 người'), ('200-299', '200 - 299 người'), ('300-999', '300 - 999 người'), ('1000-4999', '1000 - 4999 người'), ('>5000', '5000 người')], max_length=20, verbose_name='Quy mô lao động')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('private', 'Tư nhân trong nước'), ('foreign', 'Đầu tư nước ngoài'), ('state', 'Cổ phần vốn góp của nhà nước (trên 50% vốn điều lệ)'), ('other', 'Loại hình khác')], max_length=50, verbose_name='Loại hình doanh nghiệp')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Góp ý chung')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Tên doanh nghiệp')),
                ('year_established', models.PositiveIntegerField(verbose_name='Năm thành lập')),
                ('business_address', models.TextField(verbose_name='Địa chỉ của Doanh nghiệp')),
                ('respondent_name', models.CharField(max_length=255, verbose_name='Họ và tên người trả lời')),
                ('email', models.EmailField(max_length=254, verbose_name='Địa chỉ e-mail (thư điện tử)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], verbose_name='Tầm nhìn')),
                ('mission', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], verbose_name='Sứ mệnh')),
                ('strategic_goals', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], verbose_name='Mục tiêu chiến lược')),
            ],
        ),
    ]
