# Generated by Django 3.1.2 on 2024-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyoperation',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-19 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='mission',
            field=models.IntegerField(choices=[(1, '1 - Hoàn toàn không đồng ý'), (2, '2 - Rất không đồng ý'), (3, '3 - Không đồng ý'), (4, '4 - Trung lập'), (5, '5 - Đồng ý'), (6, '6 - Rất đồng ý'), (7, '7 - Hoàn toàn đồng ý')], verbose_name='Sứ mệnh: Doanh nghiệp không có sứ mệnh rõ ràng từ khi thành lập đến nay'),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='strategic_goals',
            field=models.IntegerField(choices=[(1, '1 - Hoàn toàn không đồng ý'), (2, '2 - Rất không đồng ý'), (3, '3 - Không đồng ý'), (4, '4 - Trung lập'), (5, '5 - Đồng ý'), (6, '6 - Rất đồng ý'), (7, '7 - Hoàn toàn đồng ý')], verbose_name='Mục tiêu chiến lược: Doanh nghiệp không có mục tiêu chiến lược rõ ràng'),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='vision',
            field=models.IntegerField(choices=[(1, '1 - Hoàn toàn không đồng ý'), (2, '2 - Rất không đồng ý'), (3, '3 - Không đồng ý'), (4, '4 - Trung lập'), (5, '5 - Đồng ý'), (6, '6 - Rất đồng ý'), (7, '7 - Hoàn toàn đồng ý')], verbose_name='Tầm nhìn: Doanh nghiệp không có tầm nhìn rõ ràng từ thời điểm thành lập đến nay'),
        ),
    ]
