# Generated by Django 3.1.2 on 2024-11-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20241119_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='competitive_advantage',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Bản chất của lợi thế cạnh tranh'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='core_values',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Xác định giá trị cốt lõi'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='core_values_building',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Xây dựng giá trị cốt lõi'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='customer_service',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Chăm sóc khách hàng'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='innovation_capacity',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Năng lực đổi mới sáng tạo'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='job_description',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Mô tả công việc'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='marketing_level',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Mức độ tiếp thị'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='operational_process',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Quy trình vận hành'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='organizational_chart',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Sơ đồ tổ chức'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='performance_measurement',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Hiệu quả đo lường'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='r_and_d_spending',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Chi tiêu cho nghiên cứu và phát triển'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='technology_absorption',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Khả năng hấp thụ công nghệ mới'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='technology_use',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Sử dụng công nghệ'),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='value_chain',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Độ rộng của chuỗi giá trị'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='business_address',
            field=models.CharField(max_length=255, verbose_name='Địa chỉ của Doanh nghiệp'),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='mission',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Sứ mệnh của Doanh nghiệp'),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='strategic_goals',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Mục tiêu chiến lược của Doanh nghiệp'),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='vision',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1', max_length=1, verbose_name='Tầm nhìn của Doanh nghiệp'),
        ),
    ]
