# Generated by Django 4.2.16 on 2025-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VnData',
            fields=[
                ('id_key', models.IntegerField(blank=True, db_column='id_key', primary_key=True, serialize=False, unique=True)),
                ('id', models.CharField(blank=True, db_column='ID', max_length=50, null=True)),
                ('index', models.CharField(blank=True, db_column='Index', max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('value', models.FloatField(blank=True, db_column='Value', null=True)),
            ],
            options={
                'db_table': 'VN_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VnIndicators',
            fields=[
                ('group', models.CharField(blank=True, db_column='Group', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('index', models.CharField(blank=True, db_column='Index', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=128, null=True)),
                ('vietnamese', models.CharField(blank=True, db_column='Vietnamese', max_length=128, null=True)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=50, null=True)),
                ('oldest_year', models.IntegerField(blank=True, db_column='Oldest_year', null=True)),
                ('latest_year', models.IntegerField(blank=True, db_column='Latest _year', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=128, null=True)),
            ],
            options={
                'db_table': 'VN_indicators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VnProvince',
            fields=[
                ('id', models.CharField(blank=True, db_column='ID', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=50, null=True)),
                ('province', models.CharField(blank=True, db_column='Province', max_length=50, null=True)),
            ],
            options={
                'db_table': 'VN_province',
                'managed': False,
            },
        ),
    ]
