# Generated by Django 4.2.16 on 2025-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietnam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VnGroup',
            fields=[
                ('id', models.CharField(blank=True, db_column='id', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('group', models.CharField(blank=True, db_column='group', max_length=50, null=True)),
                ('indicators', models.CharField(blank=True, db_column='indicators', max_length=128, null=True)),
                ('weight', models.FloatField(blank=True, db_column='weight', null=True)),
                ('status', models.IntegerField(blank=True, db_column='status', null=True)),
            ],
            options={
                'db_table': 'VN_group',
                'managed': False,
            },
        ),
    ]
