# Generated by Django 4.2.16 on 2025-03-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vietnam', '0002_vngroup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vndata',
            table='vn_data',
        ),
        migrations.AlterModelTable(
            name='vngroup',
            table='vn_group',
        ),
        migrations.AlterModelTable(
            name='vnindicators',
            table='vn_indicators',
        ),
        migrations.AlterModelTable(
            name='vnprovince',
            table='vn_province',
        ),
    ]
